In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
train = np.random.randint(0,100, (25,2)).astype(np.float32) #rand mang 2 chieu 25 ptu
train

array([[44., 31.],
       [31., 77.],
       [40., 19.],
       [ 3., 21.],
       [44.,  3.],
       [58., 80.],
       [ 6., 52.],
       [91., 16.],
       [56., 18.],
       [66., 13.],
       [63., 63.],
       [65., 35.],
       [41., 55.],
       [57., 60.],
       [53., 22.],
       [91., 65.],
       [17., 23.],
       [77., 46.],
       [90., 59.],
       [13., 98.],
       [51., 36.],
       [13., 44.],
       [68., 39.],
       [79., 62.],
       [20., 36.]], dtype=float32)

In [6]:
ketqua = np.random.randint(0,2, (25)).astype(np.float32)
ketqua

array([0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1.], dtype=float32)

In [8]:
red = train[ketqua.ravel() == 1]
red

array([[40., 19.],
       [ 3., 21.],
       [ 6., 52.],
       [56., 18.],
       [66., 13.],
       [63., 63.],
       [65., 35.],
       [57., 60.],
       [53., 22.],
       [77., 46.],
       [90., 59.],
       [51., 36.],
       [20., 36.]], dtype=float32)

In [9]:
plt.scatter()

TypeError: scatter() missing 1 required positional argument: 'y'

In [11]:
print red[:,1]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1127650865.py, line 1)